### ISSUE TITLE
Data Augmentation 실험

### ISSUE THREAD

**Issue by syous154** [boostcampaitech7/level2-cv-semanticsegmentation-cv-14-lv3#15]
## Background
- Data Augmentation 실험할 예정 (baseline 기준)
- 베이스라인 모델, 배치사이즈 1, 에폭 우선 20, 이미지 512
- Trapezaid - Trapezium와 Triquetrum - Pisiform의 겹치는 부분의 성능이 어떻게 변하는지가 중요해 보임

## Todo
- [x] Base 
- [x] ElasticTransform: 이미지를 고무처럼 변형하여 공간 왜곡을 적용
- [x] Sharpen: 이미지의 가장자리를 강조하여 선명도를 높임
- [x] CLAHE: 이미지의 대비를 향상시켜 어두운 영역과 밝은 영역의 디테일을 개선
- [x] Rotate: 이미지를 지정된 각도 범위 내에서 회전
- [x] Emboss: 이미지에 양각 효과를 적용하여 입체감 부여
- [x] GridDistort: 이미지에 그리드 기반의 왜곡을 적용하여 비정형적인 변형
- [x] RandomBrightnessContrast: 이미지의 밝기와 대비를 무작위로 조절
- [x] HorizontalFlip: 이미지를 좌우로 반전
- [x] Unsharp_masking
- [x] 최적의 Augmentation 조합 찾기 (CLAHE, HorizonFilp, Rotate는 기본으로 해도 될듯?)
- [x] CLAHE, HorizonFilp, Rotate = base
- [x] base + GridDistortion
- [x] base + Elastic
- [x] base + GridDistortion + Elastic

## Result
![image](https://github.com/user-attachments/assets/c5b71882-0995-4e93-92d3-37baa9d99da6)
![image](https://github.com/user-attachments/assets/0c11792d-6c92-446d-a65e-8ac0dc684cdb)

- 수치상으로 가장 높은 Data Augmentation 기법은 HoriontalFilp과 base + GridDistortion + Elastic임을 확인
- 이 두 가지 방법을 적용해보며 학습을 진행하면 좋을 듯함
