### ISSUE TITLE
Streamlit을 이용한 test 이미지 오버레이 시각화

### ISSUE THREAD

**Issue by zangzoo** [boostcampaitech7/level2-cv-semanticsegmentation-cv-14-lv3#18]
## Background
- 결과 테스트 이미지에 씌워서 편하게 보기

## Todo
- [x] output.csv 파일의 예측 RLE를 test 이미지에 오버레이
- [x] 마스크 오버레이 슬라이드 바 생성
- [x] 시각화 on/off 기능

## See also
- <img width="1718" alt="스크린샷 2024-11-15 오후 6 43 35" src="https://github.com/user-attachments/assets/ed650429-664c-44c4-ab0d-e0f2ca9a5ff6">
