### ISSUE TITLE
손목 뼈 탐색을 위한 2-stage 방식 추가

### ISSUE THREAD

**Issue by taehan79-kim** [boostcampaitech7/level2-cv-semanticsegmentation-cv-14-lv3#35]
## Background
- 문제 정의 : 학습된 모델에서 손목 뼈 부분에서 성능이 잘 나오지 않는 문제가 발생함
- 가설 설정 : 손목 뼈를 중점으로 그 부분만 학습하는 모델을 하나 더 학습 시킨 뒤 결과를 앙상블하면 성능이 더 올라갈 것이다.
- 실험 설계 : 현재 학습된 best 모델을 기준으로 RoI(Region of Interest) 영역을 추출하여 새로운 모델로 학습한 뒤 앙상블 진행

## Todo
- [x] 모델 1을 이용하여 RoI 영역 추출
- [x] 모델 2의 학습 진행
- [x] 모델 1과 모델 2의 예측 결과 앙상블

## See also
- #16
