### ISSUE TITLE
Ensemble 구현하기 : Soft, Hard, Stratified Group K Fold

### ISSUE THREAD

**Issue by namgyu-youn** [boostcampaitech7/level2-cv-semanticsegmentation-cv-14-lv3#40]
## Background
- 프로젝트 마지막에 사용할 ensemble 내용을 미리 추가할 필요가 있음.

## Todo
- [x] Ensemble : Soft voting, Hard voting
- [x] Ensemble 적용해보고 성능 변화 확인
- [ ] Ensemble : Stratified Group K Fold

## See also
- Stratified Group K Fold : T(손목이 꺾인 이미지), F(손목이 꺾이지 않은 이미지)를 train dataset에서 분할함
    -> Stratified(T, F 비율을 일정하게 유지) + Group K-Fold(교차 검증)

- [6th_CV12_GitHub](https://github.com/boostcampaitech6/level2-cv-semanticsegmentation-cv-12/tree/main/utils)
- [6th_CV03_GitHub](https://github.com/boostcampaitech6/level2-cv-semanticsegmentation-cv-03/tree/main/utils)
- [Upstage Board](https://stages.ai/en/competitions/338/board/community/post/2884)
