### ISSUE TITLE
Wandb Sweep

### ISSUE THREAD

**Issue by mooniswan** [boostcampaitech7/level2-cv-semanticsegmentation-cv-14-lv3#42]
## Background
- K-fold Cross Validation 전 최적의 모델 파라미터 조합 탐색 필요
- Wandb sweep을 통한 하이퍼파라미터 최적화 진행
- 주요 탐색 대상: lr, scheduler, weight_decay 등

## Todo
- [x] sweep_config.yaml 파일 설정
- [x] Sweep 작동 확인
- [x] 최적 파라미터 조합 확인
    * Wandb UI에서 best performance 확인

## See also
- #33 
- branch 'sweep' 에서 진행함
