### ISSUE TITLE
Data Cleaning (Remove Outlier)

### ISSUE THREAD

**Issue by namgyu-youn** [boostcampaitech7/level2-cv-semanticsegmentation-cv-14-lv3#57]
## Background
1. 학습 도중 worst_sample을 통해서, 채원(@mooniswan) 님이 train dataset에 특이한 sample이 일부 존재함을 확인함.
- 장신구(반지, 매니큐어)로 인해서 X-ray에 방해가 되는 경우
- 보형물 등으로 인해서 뼈의 모양이 왜곡되는 경우

2. 태환(@taehan79-kim) 님이 test image file을 확인해본 결과, '1'의 특이한 경우는 test dataset에서는 발견되지 않는 특징으로 확인됨. -> Outlier 가능성

3. 직접 train, test image를 모두 확인해본 결과, test image는 상당히 깨끗함을 확인함. 그러나 train image에서는 상당한 특이 샘플이 확인됨. ->   train에만 **outlier**가 있음을 판단함.

5.  따라서 이를 제거하고 모델을 학습시키면 성능이 개선될 것이라고 판단됨.

### Case 01 : 손가락 끝 마디가 인식되기 어려운 경우 : 매니큐어, 손톱
- ID069/image1661735964312.png
- ID73/image1661736368856
- ID345/image1664932982615
- ID387/image1665536734529
- ID387/image1665536751182
- ID429/image1666059783189
- ID429/image1666059811309
- ID459
- ID523
- ID543

### Case 02 : 손가락 2~3번째 마디가 인식되기 어려운 경우 : 반지
- ID363image1664935962797

### Case 03 : 손가락 끝 마디 : 여백이 부족해 끝 마디가 일부 짤린 경우
- ID396/image1665538845008
- ID397/image1665538920029
- ID416/image1666055534030

### Case 04 : 손 전체 : 이미지가 훼손되어 noise(실선)가 있는 경우
- ID430/image1666059865789
- ID430/image1666059889440

### Case 05 : Radius, Ulna : 보형물이 있어 인식되기 어려운 경우
- ID487/image1666661955150

### Case 01 : 매니큐어(손톱) → 손가락 끝 부분 탐지 어려운 경우
- ID152/image1662342952534
- ID273/image1664154611151

## To-do
- [x]  모델들이 학습한 내용에서 worst-image를 보면서 outlier라고 판단할만한지 확인
- [x]  If TRUE → Data Cleaning (제거) : 팀원들과 회의 필수
- [x]  Data Cleaning 처리한 train dataset을 이용해서 모델 학습 및 성능 변화 확인

## See also
- #
