### ISSUE TITLE
Wandb 로깅 기능 개선

### ISSUE THREAD

**Issue by mooniswan** [boostcampaitech7/level2-cv-semanticsegmentation-cv-14-lv3#8]
## Background
- Wandb에서 클래스별 성능 지표 확인이 어려움
- 실험 이름 설정이 랜덤으로 설정되어 있어 구현 필요함
- 검증 과정의 worst case 시각화 필요

## Todo
- [x] Wandb 실험 이름을 파서로 설정할 수 있도록 수정
- [x] train, val 과정에서 클래스별 Loss와 Dice metric을 구분하여 로깅
- [x] 검증 과정에서 성능이 낮은 worst samples를 Media 탭에 시각화
